CREATE TABLE ContactsDB.dic.City (
  ID INT IDENTITY
 ,CityName NVARCHAR(200) NOT NULL
 ,CONSTRAINT PK_City_ID PRIMARY KEY CLUSTERED (ID)
) ON [PRIMARY]
GO

CREATE TABLE ContactsDB.dic.Gender (
  ID INT IDENTITY
 ,GenderName NVARCHAR(10) NOT NULL
 ,CONSTRAINT PK_Gender_ID PRIMARY KEY CLUSTERED (ID)
) ON [PRIMARY]
GO

CREATE TABLE ContactsDB.dic.PhoneNumberType (
  ID INT IDENTITY
 ,TypeName NVARCHAR(100) NOT NULL
 ,CONSTRAINT PK_PhoneNumberType_ID PRIMARY KEY CLUSTERED (ID)
) ON [PRIMARY]
GO

CREATE TABLE ContactsDB.dbo.Contact (
  ID INT IDENTITY
 ,GenderID INT NOT NULL
 ,CityID INT NULL DEFAULT (NULL)
 ,Firstname NVARCHAR(100) NOT NULL
 ,Lastname NVARCHAR(100) NOT NULL
 ,DOB DATE NOT NULL
 ,Address NVARCHAR(500) NULL DEFAULT (NULL)
 ,AdditionalDetails NVARCHAR(500) NULL DEFAULT (NULL)
 ,ContactPhoto IMAGE NULL DEFAULT (NULL)
 ,IsDeleted BIT NOT NULL DEFAULT (0)
 ,IsFavorite BIT NOT NULL DEFAULT (0)
 ,DataCreated DATETIME NOT NULL DEFAULT (GETDATE())
 ,DataModified DATETIME NOT NULL DEFAULT (GETDATE())
 ,CONSTRAINT PK_Contact_ID PRIMARY KEY CLUSTERED (ID)
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX IDX_Contact_Address
ON ContactsDB.dbo.Contact (Address)
ON [PRIMARY]
GO

CREATE INDEX IDX_Contact_DOB
ON ContactsDB.dbo.Contact (DOB)
ON [PRIMARY]
GO

CREATE INDEX IDX_Contact_Firstname
ON ContactsDB.dbo.Contact (Firstname)
ON [PRIMARY]
GO

CREATE INDEX IDX_Contact_Lastname
ON ContactsDB.dbo.Contact (Lastname)
ON [PRIMARY]
GO

ALTER TABLE ContactsDB.dbo.Contact
ADD CONSTRAINT FK_Contact_CityID FOREIGN KEY (CityID) REFERENCES dic.City (ID)
GO

ALTER TABLE ContactsDB.dbo.Contact
ADD CONSTRAINT FK_Contact_GenderID FOREIGN KEY (GenderID) REFERENCES dic.Gender (ID)
GO

CREATE TABLE ContactsDB.dbo.PhoneNumber (
  ID INT IDENTITY
 ,PhoneNumberTypeID INT NOT NULL
 ,ContactID INT NOT NULL
 ,PhoneNumber VARCHAR(20) NOT NULL
 ,CONSTRAINT PK_PhoneNumber_ID PRIMARY KEY CLUSTERED (ID)
) ON [PRIMARY]
GO

ALTER TABLE ContactsDB.dbo.PhoneNumber
ADD CONSTRAINT FK_PhoneNumber_ContactID FOREIGN KEY (ContactID) REFERENCES dbo.Contact (ID)
GO

ALTER TABLE ContactsDB.dbo.PhoneNumber
ADD CONSTRAINT FK_PhoneNumber_PhoneNumberTypeID FOREIGN KEY (PhoneNumberTypeID) REFERENCES dic.PhoneNumberType (ID)
GO
